# Generated by Django 5.2.1 on 2025-05-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crisis',
            old_name='date',
            new_name='date_reported',
        ),
        migrations.AlterField(
            model_name='crisis',
            name='required_help',
            field=models.TextField(default='Not specified', max_length=500),
        ),
        migrations.AlterField(
            model_name='crisis',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10),
        ),
    ]
