# Generated by Django 5.2.1 on 2025-05-15 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disaster', '0002_rename_date_crisis_date_reported_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='volunteer',
        ),
    ]
